### ISSUE TITLE
fix issue with the selection of 'Other' on Money on hand/Main screen

### ISSUE THREAD

**Issue by MissyM2** [raft-tech/cfgov-refresh#14]
## Current behavior

_Background_: On the _Money on Hand/Main screen_, a user makes selections for where any money that they have at the start of the application is located: i.e. checking, savings, etc..  Once these selections are made, the user is taken to a series of _Money on hand/Input screens_, based on which items they have checked, to input amounts.  
1.  If the user selects 'Other' first and, then, 'Checking' and, then 'Savings', the 'Other' screen comes up but the 'Checking' and 'Savings' do not.
2.  The 'Checking' and 'Savings' categories appear in the _Money on hand/Balance summary screen_ with a $0 balance.

## Expected behavior

1.  All categories selected by the user on the _Money on hand/Main screen_, should appear on the list on the _Balance Summary Screen_.
2. The _Category input screens_ should appear to the user in the sequence that appear on the _Money on hand/Main screen_,. The order of the _Money on hand/Input screens_ should appear in is the order that they appear in on the _Money on hand/Main screen_, i.e. Checking, Savings, Cash, Prepaid Cards, Other (depending on which they select)

![Screen Shot 2020-04-30 at 6 47 04 PM](https://user-images.githubusercontent.com/34319929/80766268-08699c80-8b13-11ea-846f-d30f895058f6.png)
![Screen Shot 2020-04-30 at 6 45 51 PM](https://user-images.githubusercontent.com/34319929/80766231-e839dd80-8b12-11ea-8480-3ee47135d3a4.png)
![Screen Shot 2020-04-30 at 6 46 19 PM](https://user-images.githubusercontent.com/34319929/80766235-ebcd6480-8b12-11ea-8d93-d576331eba82.png)

**Comment by mgreen-simplethread** [comment]
This should be fixed now

**Comment by MissyM2** [comment]
@mgreen-simplethread There is still a problem.  Here is the description.  I added screenshots below.

This was the test I conducted.  Added 'Other' first.  Then, added, Savings, Cash and then Checking.  The 'Other' screen came up first but not of the other options came up.  Then, the Summary screen came up.

<img src="https://user-images.githubusercontent.com/34319929/80991173-9f7d6f80-8e05-11ea-82b6-a436b9504cab.png" width="150">
<img src="https://user-images.githubusercontent.com/34319929/80991168-9ee4d900-8e05-11ea-88e9-94d04a9c4677.png" width="150">
<img src="https://user-images.githubusercontent.com/34319929/80991165-9e4c4280-8e05-11ea-9746-e1f812215122.png" width="150">
<img src="https://user-images.githubusercontent.com/34319929/80991853-aa84cf80-8e06-11ea-8390-2619a9ea3243.png" width="150">
<img src="https://user-images.githubusercontent.com/34319929/80992398-72ca5780-8e07-11ea-86e4-527420d34a21.png" width="150">
<img src="https://user-images.githubusercontent.com/34319929/80992587-bcb33d80-8e07-11ea-99d7-339e17d80d2e.png" width="150">

**Comment by LesliePerucci** [comment]
@mgreen-simplethread the money on hand icon shouldn't change when putting in the balances in your checking/savings.

**Comment by mgreen-simplethread** [comment]
@MissyM2 @LesliePerucci Both issues have been fixed on staging and it's ready for another look.

**Comment by MissyM2** [comment]
This is complete.  I selected Money on hand in the following order: other, checking, cash and savings.  The screens came up as follows:  Checking, Savings, Cash and Other.  This is correct.
